version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  deploy:
    docker:
      - image: 'circleci/node:stretch'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - restore_cache:
          key: dependency-cache-{{ checksum "client/yarn-lock.json" }}
      - run:
          name: Install Dependencies
          command: cd client && yarn
      - run:
          name: Install sshpass
          command: |
            sudo apt-get install sshpass
            # sshpass --version
      - run:
          name: Build Webpack
          command: cd client && yarn build
      - run:
          name: deploy bundle to server
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H sivananda.webfactional.com >> ~/.ssh/known_hosts
            cd client
            sshpass -p $sshPass scp dist/* sivananda@sivananda.webfactional.com:webapps/local_sivananda/avadhuta-play
workflows:
  version: 2
  commit:
    jobs:
      - deploy
